name: build

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  cargo-clippy:
    name: "Clippy (${{ matrix.rust-toolchain }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: |
          set -euo pipefail

          features=(
            ""
            "alloc"
            "std"
            "serde"
            "alloc,serde"
            "std,serde"
            "alloc,std,serde"
          )

          if [[ "${{ matrix.rust-toolchain }}" == "nightly" ]]; then
            features+=(
              "nightly"
              "nightly,alloc"
              "nightly,std"
              "nightly,serde"
              "nightly,alloc,serde"
              "nightly,std,serde"
              "nightly,alloc,std,serde"
            )
          fi

          cargo clippy --all-targets -- -D warnings

          for f in "${features[@]}"; do
            cargo clippy --all-targets --no-default-features --features "$f" -- -D warnings
          done

          if [[ "${{ matrix.rust-toolchain }}" == "nightly" ]]; then
            cargo clippy --all-targets --all-features -- -D warnings
          fi

  cargo-test:
    name: "Test (${{ matrix.name }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: stable
            rust-toolchain: stable
            cargo-flags: ""
          - name: beta
            rust-toolchain: beta
            cargo-flags: ""
          - name: nightly
            rust-toolchain: nightly
            cargo-flags: ""
          - name: 1.90.0
            rust-toolchain: 1.90.0
            cargo-flags: ""
          - name: stable release
            rust-toolchain: stable
            cargo-flags: "--release"
          - name: nightly release
            rust-toolchain: nightly
            cargo-flags: "--release"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-toolchain }}
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: |
          set -euo pipefail

          features=(
            ""
            "alloc"
            "std"
            "serde"
            "alloc,serde"
            "std,serde"
            "alloc,std,serde"
          )

          if [[ "${{ matrix.rust-toolchain }}" == "nightly" ]]; then
            features+=(
              "nightly"
              "nightly,alloc"
              "nightly,std"
              "nightly,serde"
              "nightly,alloc,serde"
              "nightly,std,serde"
              "nightly,alloc,std,serde"
            )
          fi

          cargo test --all-targets ${{ matrix.cargo-flags }}

          for f in "${features[@]}"; do
            cargo test --all-targets ${{ matrix.cargo-flags }} --no-default-features --features "$f"
          done

          if [[ "${{ matrix.rust-toolchain }}" == "nightly" ]]; then
            cargo test --all-targets ${{ matrix.cargo-flags }} --all-features
          fi

  cargo-test-no-alloc-and-no-std:
    name: Test no-alloc and no-std compatibility
    runs-on: ubuntu-latest
    env:
      ARGS: >-
        --config build.rustflags=["-C","link-arg=-nostartfiles"]
        --manifest-path tests/no-alloc-and-no-std/Cargo.toml
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          set -euo pipefail

          ! cargo build $ARGS
          cargo build $ARGS --features panic-handler
          ! cargo build $ARGS --features alloc,panic-handler
          cargo build $ARGS --features alloc,panic-handler,global-allocator,rust-eh-personality
          ! cargo build $ARGS --features alloc,std,panic-handler,global-allocator
          cargo build $ARGS --features alloc,std,global-allocator
          cargo build $ARGS --features alloc,std

  cargo-deny:
    name: Check licenses/bans/advisories/sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
          arguments: --workspace --all-features
